# -*- coding: utf-8 -*-
"""salary_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_GaQYdaOYpr7mdbHeeqITCKmzFtu94v
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PowerTransformer, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score


df=pd.read_csv("Salary Data.csv")
df.head()

X=df.drop("Salary",axis=1)
y=df["Salary"].fillna(df["Salary"].mean())


num_cols=X.select_dtypes(include=["int64", "float64"]).columns
cat_cols=X.select_dtypes(include=["object"]).columns

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

num_imputer=SimpleImputer(strategy="median")
num_imputed=pd.DataFrame(num_imputer.fit_transform(X_train[num_cols]),columns=num_cols)

print("="*100)
print("The skwness of All numerical columns:")
print("="*100)
print("The Skewness of age:")
print(num_imputed.Age.skew())
print("The skewness of Experience(year):")
print(num_imputed['Years of Experience'].skew())
print("The skewness of Salary:")
print(pd.DataFrame(y_train).skew())

print("="*100)
print("The Distribution Graph of All numerical columns:")
print("="*100)


for cols in num_cols:
  sns.kdeplot(num_imputed[cols])
  plt.title("Before power transform")
  plt.show()



sns.kdeplot(y_train)
plt.title("Before power transform")
plt.show()


numberic_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])


categorical_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown='ignore'))
])

preprocessor=ColumnTransformer([
    ("num",numberic_pipeline,num_cols),
    ("cat",categorical_pipeline,cat_cols)
])

model=Pipeline([
    ("preprocessor",preprocessor),
    ("model",LinearRegression())
])

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

R2=r2_score(y_test,y_pred)
print("="*40)
print("The R2 Sscore is :")
print( R2*100,"%")

print("="*150)

print("Actual Vs Predicted Graph")
plt.scatter(y_test,y_pred, color='blue', label='Actual vs Predicted')
m,b=np.polyfit(y_test,y_pred,1)
plt.plot(y_test, m*y_test+b, color='red', label='Regression Line')
plt.title("Actual Vs Predicted")
plt.xlabel("Actual Salary (y_test)")
plt.ylabel("Predicted Salary (y_pred)")
plt.legend()
plt.show()


print("="*150)

print("User input:")
print("="*150)

st.title("Salary Prediction App")
st.write("Enter the following details to predict salary:")

user_data={}

for cols in num_cols:
  value=st.number_input(f"Enter the {cols}:",value=0.0 )
  user_data[cols]=value

for cols in cat_cols:
  category=st.text_input(f"Enter the {cols} :")
  user_data[cols]=category

user_df=pd.DataFrame([user_data])

if st.button("Predict Salary"):
   predicted_salary=model.predict(user_df)[0]
   st.success(f"The predicted salary is: ${predicted_salary:.2f}")

