# -*- coding: utf-8 -*-
"""Sleep_Quality.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAQ3bVSCDuY9NZxgzKwppaQITHhiM6lb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, OneHotEncoder,FunctionTransformer,PowerTransformer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer


#LOAD THE DATASET

df=pd.read_csv("Sleep_Quality.csv")
df.head()

df.isnull().sum()

#Process The Dataset

df['Sleep Disorder'] = df['Sleep Disorder'].fillna('None')
df.drop('Person ID', axis=1, inplace=True)
df.drop('Gender', axis=1, inplace=True)


df.isnull().sum()

df[['systolic', 'diastolic']]=df['Blood Pressure'].str.split('/', expand=True)

df['systolic']=df['systolic'].astype('float')
df['diastolic']=df['diastolic'].astype('float')

df.drop('Blood Pressure', axis=1, inplace=True)

X=df.drop('Quality of Sleep', axis=1)
y=df['Quality of Sleep']


pt=PowerTransformer()
ft=FunctionTransformer(lambda x: x**2)

X['Heart Rate']=pt.fit_transform(X[['Heart Rate']])
X['Age']=ft.fit_transform(X[['Age']])
X['systolic']=ft.fit_transform(X[['systolic']])






num_cols=X.select_dtypes(include='number').columns
cat_cols=X.select_dtypes(include='object').columns


#Training


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)



num_cols_transformer=Pipeline(steps=[
    ('scaler', StandardScaler())

])


print("Skewness of all Numerical Columns:\n")
print(X_train[num_cols].skew())

cat_cols_transformer=Pipeline(steps=[
    ('One_Hot_encoder', OneHotEncoder(handle_unknown='ignore')),
])

preprocessor=ColumnTransformer(transformers=[
    ('num', num_cols_transformer, num_cols),
    ('cat', cat_cols_transformer, cat_cols)
])
model=Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

model.fit(X_train, y_train)



#Visualize the Data

sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()



#Prediction

y_pred=model.predict(X_test)

r2_score(y_test, y_pred)
score=cross_val_score(model, X_train, y_train, cv=5)
R2_Score=score.mean()

MAE=mean_absolute_error(y_test, y_pred)
MSE=mean_squared_error(y_test, y_pred)

print("="*100)

print(f"R2 Score: {R2_Score*100}%")
print(f"MAE: {MAE}")
print(f"MSE: {MSE}")


print("="*100)


user_input={}

for cols in num_cols:
  value=float(input(f"Enter {cols}: "))
  user_input[cols]=value
for cols in cat_cols:
  value=input(f"Enter {cols}: ")
  user_input[cols]=value
user_input=pd.DataFrame([user_input])


y_pred=model.predict(user_input)
user_input['Heart Rate'] = pt.transform(user_input[['Heart Rate']])
user_input['Age'] = user_input['Age'] ** 2
user_input['systolic'] = user_input['systolic'] ** 2


prediction=model.predict(user_input)


if user_input['Daily Steps'].iloc[0]<5000: prediction-=0.25
elif user_input['Stress Level'].iloc[0]<6: prediction-=0.5
elif user_input['Physical Activity Level'].iloc[0]<40: prediction-=0.3
elif user_input['Sleep Disorder'].iloc[0]=='Insomnia' or 'Sleep Apnea': prediction-=0.5

print(f"The predicted quality of sleep is {prediction[0]}")



if(prediction[0]>8):
  print("Good Sleep Quality")
elif(prediction[0]>6):
  print("Average Sleep Quality")
elif(prediction[0]<6):
  print("Poor Sleep Quality")
elif(prediction[0]<4.5):
  print("Very poor Sleep Quality")